### ISSUE TITLE
Documentation unclarities

### ISSUE THREAD

**Issue by kermitfrog** [omv-ysong/DeepSeaRenderer#1]
Parts of the Documentation are not quite clear: 

Variables: 

* scale_factor: can you eleborate more specifically on what exactly this does? How would I set this, if I want to simulate a specific light source?
* slab_sampling_method: does a value of 0 mean that anything within a slab has the same backscatter?
* light_spectrum_RGB: this means the values of the light source, right?
* light_RID_type: has a typo (first letter missing)
* light_positions_XYZ: are these in m?

Depth Map: I assume the values are in m as well. Is that correct?

**Comment by omv-ysong** [comment]
* scale_factor: this factor is similar to the ISO or exposure time factors in the camera, which only control the global brightness of the image. This factor aim to generate images with well distributed histogram, we make it adjustable for simulating the overexposure problem (see Fig. 11 in our paper).  If you wat to simulate a specific light source, you need to change the light_RID_type. 
* slab_sampling_method: this factor only controls the thickness of each slab (\delta z_i in Eqt. 4 in our paper), the backscatter is also refers to the slab distance to the camera, the relative pose to light source(s) and light RID. Fig. 9 in our paper shows the backscatter pattern changes rapidly when closer to the camera and appears similar when far away from the camera, denser sampling in the close range can improve the quality of the final accumulated backscatter simulation.
* light_spectrum_RGB: this factor which is obtained from your LED spectrum curve, you can understand it as the normalized color of the light.
* light_positions_XYZ: relative position of each lights to the camera, unit is in meter.

Depth Map values are also in meter, all the distance are defined in meter in our code.

**Comment by omv-ysong** [comment]
Close this issue since no further comments.
